### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by roycho87** [cocomine/TemporalKit#1]
**Describe the bug**
After installing, tab not showing in WebUI

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/cocomine/TemporalKit/assets/105740590/03c798a6-c72c-432d-9fe7-ebff2d166ae3)
![image](https://github.com/cocomine/TemporalKit/assets/105740590/dbeb67ef-50b9-40a4-b307-655db22a8395)

**Error Log**
Copy & Paste the error log in console.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 11
 - Browser [e.g. chrome, safari] chrome
 - SD Version [e.g. 1.6.0] v 1.5.1

**Additional context**

**Comment by cocomine** [comment]
I have tested and modified it. You can update to the latest version and try again. It is also recommended that you upgrade the version of stable diffusion to 1.6.0 or above.

**Comment by cocomine** [comment]
Due to no reply for a long time this issue will be marked as resolved
