### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by poyingshihuang** [cocomine/TemporalKit#2]
**Describe the bug**

**To Reproduce**
e.x.

**Expected behavior**

**Screenshots**

**Error Log**
Copy & Paste the error log in console (Black window).

**Desktop (please complete the following information):**
 - OS: [e.g. mac, window]
 - Browser [e.g. chrome, safari, firefox]
 - SD Version [e.g. 1.6.0]
 - Extended version: [e.g. 1.1]

**Additional context**

**Comment by cocomine** [comment]
No representation is made. Please make sure you are sure you need it before opening it to avoid causing confusion.
